# ==============================
# DEV Environment Configuration
# ==============================
server.port=${APPLICATION_PORT:8091}

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eden_crm_sec_crm?useSSL=false}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.default_schema=${DB_SCHEMA:eden_crm_sec_crm}

# Show SQL
spring.jpa.show-sql=true

# Mail
spring.mail.host=${EMAIL_SERVER:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME:active@eden-tech.io}
spring.mail.password=${EMAIL_PASSWORD:gaiofwlzfyqipfdf}

# Oracle Storage
oracle.storage.url=${STORAGE_URL:https://objectstorage.me-jeddah-1.oraclecloud.com/}
oracle.storage.namespace=${NAMESPACE:axcyljkipwrn}
oracle.storage.bucketName=${BUCKET_NAME:test}

# Customer Portal
customer-portal.url=${CUSTOMER_PORTAL_URL:https://edem-crm-sec-customer-portal-dev.eden-tech.io}

# Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://127.0.0.1:8761/eureka}

# Kafka
spring.kafka.producer.bootstrap-servers=${KAFKA_URL:localhost:9092}
spring.kafka.consumer.bootstrap-servers=${KAFKA_URL:localhost:9092}

# Logging - Verbose
logging.level.root=INFO
logging.level.com.eden.eden_crm_visitor_back=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.servlet.HandlerMapping=DEBUG
logging.level.org.springframework.web.servlet.HandlerAdapter=DEBUG
logging.level.org.springframework.web.servlet.HandlerExceptionResolver=DEBUG
logging.level.org.springframework.web.filter=DEBUG
logging.level.org.apache.http.wire=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
spring.mvc.log-request-details=true