spring.application.name=eden-crm-sec-crm

server.port=${APPLICATION_PORT:8091}
server.servlet.contextPath=/crm
server.shutdown=graceful

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eden_crm_sec_crm?useSSL=false}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.default_schema=${DB_SCHEMA:eden_crm_sec_crm}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=${EMAIL_SERVER:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME:active@eden-tech.io}
spring.mail.password=${EMAIL_PASSWORD:gaiofwlzfyqipfdf}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


oracle.storage.url=${STORAGE_URL:https://objectstorage.me-jeddah-1.oraclecloud.com/}
oracle.storage.namespace=${NAMESPACE:axcyljkipwrn}
oracle.storage.bucketName=${BUCKET_NAME:test}

customer-portal.url=CUSTOMER_PORTAL_URL:https://edem-crm-sec-customer-portal-test.eden-tech.io

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Feign Clients
feign.clients.documents=${DOCUMENT_SERVICE_NAME:eden-crm-sec-document}
feign.clients.crm=${CRM_SERVICE_NAME:eden-crm-sec-crm}
feign.clients.org-unit=${ORG_UNIT_SERVICE_NAME:eden-crm-sec-org-unit}
feign.clients.visitor=${VISITOR_SERVICE_NAME:eden-crm-sec-visitor}
feign.clients.patrol=${SECURITY_GUARD_SERVICE_NAME:eden-crm-sec-patrol}
feign.clients.attendance=${ATTENDANCE_SERVICE_NAME:eden-crm-sec-attendance}

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://127.0.0.1:8761/eureka}
eureka.instance.prefer-ip-address=true

keycloak.admin-cli-secret=s7QErkZaQkZV80E6yHs6hgXnRvs33BzN
keycloak.auth-url=https://keycloak-test.eden-tech.io
keycloak.realm=eden-crm-sec-users

# Kafka Configuration
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=crm-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages='*'
spring.kafka.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
# TODO :: may be REMOVE in future, This is asked from yasser and I don't know why doing it :D as its very bad for performance
spring.kafka.producer.acks=all
