spring.application.name=eden-crm-sec-crm-back

server.port=${APPLICATION_PORT:8093}
server.servlet.contextPath=/crm
server.shutdown=graceful

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eden_crm_sec_crm?useSSL=false}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.default_schema=${DB_SCHEMA:eden_crm_sec_crm}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=${EMAIL_SERVER:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME:active@eden-tech.io}
spring.mail.password=${EMAIL_PASSWORD:wzgilzypklervtjr}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


oracle.storage.url=${STORAGE_URL:https://objectstorage.me-jeddah-1.oraclecloud.com/}
oracle.storage.namespace=${NAMESPACE:axcyljkipwrn}
oracle.storage.bucketName=${BUCKET_NAME:test}

customer-portal.url=CUSTOMER_PORTAL_URL:https://edem-crm-sec-customer-portal-test.eden-tech.io