# ==============================
# TEST Environment Configuration
# ==============================
server.port=${APPLICATION_PORT:8091}

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eden_crm_sec_crm?useSSL=false}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.default_schema=${DB_SCHEMA:eden_crm_sec_crm}

# Show SQL
spring.jpa.show-sql=true


# Feign Clients
feign.clients.documents=${DOCUMENT_SERVICE_NAME:eden-crm-sec-document}
feign.clients.crm=${CRM_SERVICE_NAME:eden-crm-sec-crm}
feign.clients.org-unit=${ORG_UNIT_SERVICE_NAME:eden-crm-sec-org-unit}
feign.clients.visitor=${VISITOR_SERVICE_NAME:eden-crm-sec-visitor}
feign.clients.patrol=${SECURITY_GUARD_SERVICE_NAME:eden-crm-sec-patrol}
feign.clients.attendance=${ATTENDANCE_SERVICE_NAME:eden-crm-sec-attendance}
feign.clients.c2=${C2_SERVICE_NAME:eden-crm-sec-c2}
feign.clients.image-comparison=${IMAGE_COMPARISON_SERVICE_NAME:eden-crm-sec-image-comparison}

# Mail
spring.mail.host=${EMAIL_SERVER:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME:active@eden-tech.io}
spring.mail.password=${EMAIL_PASSWORD:gaiofwlzfyqipfdf}

# Oracle Storage
oracle.storage.url=${STORAGE_URL:https://objectstorage.me-jeddah-1.oraclecloud.com/}
oracle.storage.namespace=${NAMESPACE:axcyljkipwrn}
oracle.storage.bucketName=${BUCKET_NAME:test}

# Customer Portal
customer-portal.url=${CUSTOMER_PORTAL_URL:https://edem-crm-sec-customer-portal-test.eden-tech.io}

# Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://127.0.0.1:8761/eureka}

# Kafka
spring.kafka.producer.bootstrap-servers=${KAFKA_URL:localhost:9092}
spring.kafka.consumer.bootstrap-servers=${KAFKA_URL:localhost:9092}

# Logging - Moderate
logging.level.root=INFO
logging.level.com.eden.eden_crm_visitor_back=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.DispatcherServlet=INFO
logging.level.org.springframework.web.servlet.HandlerMapping=INFO
logging.level.org.springframework.web.servlet.HandlerAdapter=INFO
logging.level.org.springframework.web.servlet.HandlerExceptionResolver=INFO
logging.level.org.springframework.web.filter=INFO
logging.level.org.apache.http.wire=INFO
logging.level.org.springframework.web.client.RestTemplate=INFO
spring.mvc.log-request-details=false